site_name: nextExplorer
theme:
  name: material
docs_dir: source
nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Features': 'features.md'
  - 'User Guide': 'user-guide.md'
  - 'Admin Guide': 'admin-guide.md'
  - 'Settings': 'settings.md'
  - 'Authentication (OIDC)': 'oidc.md'
  - 'Authelia (OIDC)': 'oidc-authelia.md'
  - 'Reverse Proxy': 'reverse-proxy.md'
  - 'Configuration': 'configuration.md'
  - 'Deployment': 'deployment.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Releases': 'releases.md'
  - 'Screenshots': 'screenshots.md'
plugins:
  - search
