site_name: nextExplorer
theme:
  name: material
docs_dir: source
nav:
  - 'Home': 'index.md'
  - 'Releases': 'releases.md'
  - 'Features': 'features.md'
  - 'Deployment': 'deployment.md'
  - 'Reverse Proxy': 'reverse-proxy.md'
  - 'OIDC': 'oidc.md'
plugins:
  - search
